version: '3.9'
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./
    depends_on:
      - db
      - socket
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
  socket:
    depends_on:
      - redis
    container_name: socket
    build:
      context: ./socket
    volumes:
      - ./socket:/usr/src/app
    ports:
      - 3000:3000
  redis:
    image: redis:5
    ports:
      - "6382:6382"
  db:
    build:
      context: ./Database
    container_name: db
    volumes:
      - ./database/meraki.sql:/docker-entrypoint-initdb.d/meraki.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: meraki
      TZ: America/Sao_Paulo
      TIMEZONE: America/Sao_Paulo
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80
